# Generated by Django 5.1.6 on 2025-04-16 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0004_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('translated_text1', models.TextField()),
                ('translated_text2', models.TextField()),
                ('translated_text3', models.TextField()),
                ('language1', models.CharField(max_length=10)),
                ('language2', models.CharField(max_length=10)),
                ('language3', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('receiver1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_group_messages_1', to=settings.AUTH_USER_MODEL)),
                ('receiver2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_group_messages_2', to=settings.AUTH_USER_MODEL)),
                ('receiver3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_group_messages_3', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_group_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='groupConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, max_length=100, null=True)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_conversations_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_conversations_user2', to=settings.AUTH_USER_MODEL)),
                ('user3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_conversations_user3', to=settings.AUTH_USER_MODEL)),
                ('user4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_conversations_user4', to=settings.AUTH_USER_MODEL)),
                ('messages', models.ManyToManyField(to='translator.groupmessage')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('group_name', 'user1', 'user2', 'user3', 'user4'), name='unique_group_conversation')],
            },
        ),
    ]
