# Generated by Django 5.1.6 on 2025-04-16 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0005_groupmessage_groupconversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupconversation',
            name='user3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_conversations_user3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupconversation',
            name='user4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_conversations_user4', to=settings.AUTH_USER_MODEL),
        ),
    ]
