# Generated by Django 5.1.6 on 2025-04-16 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0006_alter_groupconversation_user3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessage',
            name='receiver2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_group_messages_2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='receiver3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_group_messages_3', to=settings.AUTH_USER_MODEL),
        ),
    ]
