# Generated by Django 5.1.6 on 2025-04-16 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0007_alter_groupmessage_receiver2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='language_text',
            field=models.CharField(default='English', max_length=150),
        ),
    ]
