# Generated by Django 5.1.6 on 2025-04-18 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0008_customuser_language_text'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='groupconversation',
            name='unique_group_conversation',
        ),
    ]
